# Generated by Django 4.1.7 on 2023-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naga", "0005_remove_nagadata_id_alter_nagadata_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="nagadata",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nagadata", name="title", field=models.CharField(max_length=100),
        ),
    ]
