# Generated by Django 4.1.7 on 2023-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naga", "0006_nagadata_id_alter_nagadata_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nagadata",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
