# Generated by Django 4.1.7 on 2023-04-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naga", "0007_alter_nagadata_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nagadata",
            name="description",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="nagadata", name="title", field=models.CharField(max_length=100),
        ),
    ]
